### ISSUE TITLE
Prvasici

### ISSUE THREAD

**Issue by kicdu** [dkorunic/e-dnevnik-bot#13]
Bok Dinko, jesi razmisljao mozda doraditi bot-a da podrzi setup za prvasice koji nemaju aktivne razrede? get na /class vraca 302 redirect na  /grade/all.

**Comment by dkorunic** [comment]
Donedavno je radio dobro i za prvasice bez aktivnih razreda, medjutim vjerojatno je vezano uz redizajn.. Javim ti se povratno da vidim sto mozemo sloziti.

**Comment by kicdu** [comment]
Ipak login problemi, e-dnevnik-bot radi ispravno. Hvala Dinku na brzoj reakciji i pomoci.

**Comment by dkorunic** [comment]
Nastavno na ovo, bolja detekcija (i ispis) gresaka pri loginu: https://github.com/dkorunic/e-dnevnik-bot/commit/a4c0498d77dc1383d1aebe358218cfca5f2d0a84
