### ISSUE TITLE
Docker kontejner se stalno restarta

### ISSUE THREAD

**Issue by mojrs10** [dkorunic/e-dnevnik-bot#2]
Kreirao sam kontejner prema uputama, ali isti se stalno restarta. Nikakav log na žalost nisam uspio uloviti.

**Comment by dkorunic** [comment]
@mojrs10 Mozes li mi dati vise informacija? Dakle, povukao si container sa Docker Huba prema uputama (https://github.com/dkorunic/e-dnevnik-bot#running-as-a-docker-container) sa ispravnom konfiguracijom i kad se pokrene, odmah se zatvori i nema ga vise u `docker ps`? Ako je tome tako, ajde molim te onda nemoj pokrenuti sa `--detach`, ostavi sve ostale parametre i pejstaj ovdje u issue sto se desava.

**Comment by nsturko** [comment]
Rekao bih da je problem ili sa konfiguracijskom fajlom (nisu uneseni ispravni podaci) ili zbog lokacije s koje se pokreće doker. Meni se restartao jer sam pokretao docker unutar ednevnik direktorija u kojem je bio i .ednevnik.toml i u tom slučaju se kreirao novi ednevnik direktorij u kojem nije bilo .ednevnik.toml konfiguracijska datoteka ($pwd/ednevnik/ednevnik umjesto $pwd/ednevnik).

**Comment by mojrs10** [comment]
Bilo je problema samim postavkama kod izrade kontejnera i nakon malo isprobavanja proradilo je sa ovim postavkama (putanja je malo prilagođena):
docker run --detach \\
    --name=ednevnik \\
    --network=host \\
    --volume "/sharedfolders/docker_postavke/ednevnik:/ednevnik" \\
    --restart unless-stopped \\
    dkorunic/e-dnevnik-bot \\
    --daemon \\
    --verbose \\
    --database /ednevnik/.e-dnevnik.db \\
    --conffile /ednevnik/.e-dnevnik.toml

Povezao sam ga za sad sa Telegramom pa slijedi malo testiranja.
