### ISSUE TITLE
Više škola za jednog učenika

### ISSUE THREAD

**Issue by ghost** [dkorunic/e-dnevnik-bot#5]
Hi Dinko, hvala puno na ovome, definitivno će olakšati praćenje stanja u dnevniku.

Upogonio sve kroz docker-compose, radi super, no primjetio sam issue da se ne refresha stanje ukoliko učenik pohađa dvije škole istovremeno.
Uredno stižu obavijesti za dijete sa jednim razredom, no za drugo nikad nije došlo ništa.

Dijete mi pohađa uz osnovnu i glazbenu, kod nje nakon logina u browseru dobivam na odabir za koji razred želim info.

![image](https://user-images.githubusercontent.com/614781/221935611-a2429a64-1a2b-4b9b-a023-42696b3334a1.png)

Upalio verbose log pa dobijem ovaj error:

{"level":"warn","time":"2023-02-28T17:26:07Z","message":"error scraping data for user xxxxx@skole.hr: All attempts fail:\n#1: vCalendar not found\n#2: could not find CSRF token\n#3: could not find CSRF token"}

Kroz browser u dev consoli vidim da odabir razreda radi HTTP request na

https://ocjene.skole.hr/class_action/[:id razreda:]/course
Što završi kao 302 redirect nazad na https://ocjene.skole.hr/course

Koliko vidim razlika je u tome što učenik sa jednim aktivnim razredom ima automatski landing page na https://ocjene.skole.hr/course

Dok učenik s 2 aktivna razreda ima landing page podešen kao:
https://ocjene.skole.hr/class 

Ovaj drugi link radi, ukoliko ga se unese ručno, čak i za učenika sa jednim razredom, pa vjerujem da se može iskoristiti za debugging

**Comment by dkorunic** [comment]
Da nazalost nemam ni jedno dijete koje ide istovremeno u dvije skole pa sam skroz previdio takvu mogucnost :-) U svakom slucaju treba dodatnog koda koji scrapea i izvlaci svaki razred iz https://ocjene.skole.hr/course. Nazalost necu moci takvo nesto bez tvoje suradnje pa ako ti nije problem javi se u mail..

**Comment by ghost** [comment]
Ma nikakav problem, least I can do :)

Samo info, znači kod učenika koji pohađa samo jednu školu, nakon logina kroz browser, može se ručno otvoriti ovaj URL:
https://ocjene.skole.hr/class
E-dnevnik onda prikaže istu listu za odabir razreda kao i kod učenika koji pohađa dvije škole.

Javim se svakako i mailom još pa pošaljem još detalja ako će biti potrebno.

Tnx.

**Comment by dkorunic** [comment]
Prvi dio veceg refaktora koji se bavi s ovim je upravo sjeo u https://github.com/dkorunic/e-dnevnik-bot/commit/9f10336215438841858e6a5e1420b82f06bff300. Javim se za beta testing..

**Comment by ghost** [comment]
Isprobao nabrzaka testni build, čini se da ovaj dio sad radi kako treba, odnosno error koji je ranije bio prisutan se više ne javlja. Pustim da se vrti u pozadini par dana da uhvati activitya malo pa javim ako bude kakvih issuea.

**Comment by dkorunic** [comment]
Da ne duljimo, [0.9.0](https://github.com/dkorunic/e-dnevnik-bot/releases/tag/v0.9.0) bi trebao u potpunosti podrzavati vise aktivnih/upisanih razreda, koliko god ih bilo, a obavijesti ce se slati u obliku "predmet / razred" za ucenike koji imaju vise aktivnih razreda. Molim te, kad stignes isprobaj i javi dojmove nakon bete :)

**Comment by dkorunic** [comment]
Rijeseno, zatvaram ticket.
