### ISSUE TITLE
Discord bot ne šalje obavijesti

### ISSUE THREAD

**Issue by bbarun** [dkorunic/e-dnevnik-bot#7]
Bok,

imao sam ideju sklepati nešto sam, pa sam naletio na ovaj projekt, svaka čast, nadam se da ću moći doprinijeti u budućnosti. Dakle, na M1 Macbooku, Ventura 13.6. nikako ne mogu dobiti Discord obavijest, konfiguracija, pokretanje i Discord u screenshotu, nadam se da je sve vidljivo, verbose logging uključen, nema errora ni warninga, testna poruka stiže, vidljivo iz priloženog. Ista stvar ako pokrećem u Dockeru i nativno iz konzole.

![Screenshot 2023-10-19 at 17 18 23](https://github.com/dkorunic/e-dnevnik-bot/assets/3776298/b9ccb3db-e008-4610-a45e-39a7607ccafc)

**Comment by dkorunic** [comment]
Bok Bozo, ovo sve dobro izgleda. Bot funkcionira tako da na prvom runu sve stare obavijesti kod sebe oznaci kao vidjene tako da ne bi odjednom dobio stotine poruka bezveze. Od sad nadalje sve sto bude novo bi trebao vidjeti najnormalnije.

**Comment by bbarun** [comment]
Super, uploadao redactani SS koji nema imena djece u konzoli, onda možda samo sugestija da to negdje bude eksplicitno navedeno u dokumentaciji da nema načina povući nulto stanje, da se samo nove ocjene i eventi mogu dobiti, također -V flag ne radi, iako je naveden u helpu, dok --verbose radi dobro. 

Hvala, zatvaram issue.

**Comment by dkorunic** [comment]
Nulto stanje -- apsolutno, napisati cu u dokumentaciji. Razlog tome je da svi sustavi (Telegram, Discord, Slack ...) imaju API limite i throttlaju requestove po sekundi. Kad bi omogucili da prvi run salje, to bi rezultiralo i sa porukama koje nije moguce poslati i eventualno cak i sa blacklistom user-ID-a na tim servisima, pa zato i ne postoji mogucnost forsiranja takvog neceg.

Sto se tice `-V` flaga, to je malo `-v` i sigurno radi:

```
$ ./e-dnevnik-bot -v
{"level":"info","time":"2023-10-19T18:10:56+02:00","message":"e-dnevnik-bot v0.10.2 107d752.dirty, built on: 2023-10-19T16:10:17Z"}
{"level":"debug","time":"2023-10-19T18:10:56+02:00","message":"GOMAXPROCS limit is set to: 20"}
{"level":"info","time":"2023-10-19T18:10:56+02:00","message":"Configuration: Discord messenger enabled"}
...
```

Kao sto mozes vidjeti, upalio je debug level poruka.
