### ISSUE TITLE
Google calendar upute

### ISSUE THREAD

**Issue by nsturko** [dkorunic/e-dnevnik-bot#8]
Pozdrav,

Potrebno li kreirati vlastiti calendar_credentials.json ili možemo koristiti postojeći? 
Moram priznati da mi je ovaj koncept pomalo nejasan, pa sam napravio vlastiti calendar_credentials.json međutim mislim da mi fali dio (sensitive scope), za što moram odraditi verifikaciju...

Lp

**Comment by dkorunic** [comment]
@nsturko Jos je beta s obzirom da se ceka Google Security Team da dovrsi verifikaciju projekta, ali napisati cu ovdje upute i slobodno se javi mailom ili cime god ako zapnes.

Postupak je sljedeci:
- napraviti si kakav god zelis Google Calendar, dakle moze imati proizvoljno ime ali ja bih savjetovao da bude odvojen od ostalih kalendara u zaseban, da ga mozes "dijeliti" sa drugima i eventualno gasiti/paliti po potrebi,

- na "serveru" gdje vrtis app, trebas updateati na [v0.10.2](https://github.com/dkorunic/e-dnevnik-bot/releases/tag/v0.10.2) i uz aplikaciju spremiti i ovu datoteku: https://raw.githubusercontent.com/dkorunic/e-dnevnik-bot/main/calendar_credentials.json

- nakon toga, prvi run da pokupimo Oauth2 token mora biti interaktivan i mora biti na tvom desktopu koji mora moci otvoriti browser da odaberes Google account; pri tome ne treba nikakva postojeca baza alertova, ovaj run ce biti samo da pokupimo  i spremimo token koji ces kopirati kasnije na server,

- skopiras .e-dnevnik.toml sa servera na desktop zajedno sa app-om i dodas blok za kalendar (vidi primjer na dnu https://raw.githubusercontent.com/dkorunic/e-dnevnik-bot/main/.e-dnevnik.toml.example, doslovno samo blok i ime kalendara u navodnicima)

- desktopu gdje zavrtis app treba biti i calendar_credentials.json (spomenut gore), bez njega aplikacija se ne moze identificirati Google Calendar API-ju

- pokrenes desktop app interaktivno, bez ikakvih parametara i on ce ti otvoriti browser tab koji ce promptati koji zelis account/token -- sve dozvole moras dati da bi radilo (bit ce dva scopea, jedan za listanje svih kalendara i jedan za editiranje/dodavanje eventova u kalendare)

- odaberes sve, slozis se sa svime, prihvatis da nije verificirani app i app ce zavrsiti i izaci, a ti bi trebao imati calendar_token.json spremljen uz aplikaciju

- calendar_token.json i calendar_credentials.json te puni .e-dnevnik.toml prebacis na server i od tad nadalje vise ne treba refreshati token na ruke.

**Comment by dkorunic** [comment]
Naravno, znam da nije bas ocito ali od kad se upali ova integracija, ona vrijedi za sve *nove* eventove tipa ispit, stari se nece nikad dodati :-) Eventualno mogu omoguciti da se iz baze obrise odredjeni period starih eventova pa da se moze ponovo izvrtiti i poslati/dodati, to je vrlo lako moguce dodati.

**Comment by nsturko** [comment]
> @nsturko Jos je beta s obzirom da se ceka Google Security Team da dovrsi verifikaciju projekta, ali napisati cu ovdje upute i slobodno se javi mailom ili cime god ako zapnes.
> 
> Postupak je sljedeci:
> 
> * napraviti si kakav god zelis Google Calendar, dakle moze imati proizvoljno ime ali ja bih savjetovao da bude odvojen od ostalih kalendara u zaseban, da ga mozes "dijeliti" sa drugima i eventualno gasiti/paliti po potrebi,
> * na "serveru" gdje vrtis app, trebas updateati na [v0.10.2](https://github.com/dkorunic/e-dnevnik-bot/releases/tag/v0.10.2) i uz aplikaciju spremiti i ovu datoteku: https://raw.githubusercontent.com/dkorunic/e-dnevnik-bot/main/calendar_credentials.json
> * nakon toga, prvi run da pokupimo Oauth2 token mora biti interaktivan i mora biti na tvom desktopu koji mora moci otvoriti browser da odaberes Google account; pri tome ne treba nikakva postojeca baza alertova, ovaj run ce biti samo da pokupimo  i spremimo token koji ces kopirati kasnije na server,
> * skopiras .e-dnevnik.toml sa servera na desktop zajedno sa app-om i dodas blok za kalendar (vidi primjer na dnu https://raw.githubusercontent.com/dkorunic/e-dnevnik-bot/main/.e-dnevnik.toml.example, doslovno samo blok i ime kalendara u navodnicima)
> * desktopu gdje zavrtis app treba biti i calendar_credentials.json (spomenut gore), bez njega aplikacija se ne moze identificirati Google Calendar API-ju
> * pokrenes desktop app interaktivno, bez ikakvih parametara i on ce ti otvoriti browser tab koji ce promptati koji zelis account/token -- sve dozvole moras dati da bi radilo (bit ce dva scopea, jedan za listanje svih kalendara i jedan za editiranje/dodavanje eventova u kalendare)
> * odaberes sve, slozis se sa svime, prihvatis da nije verificirani app i app ce zavrsiti i izaci, a ti bi trebao imati calendar_token.json spremljen uz aplikaciju
> * calendar_token.json i calendar_credentials.json te puni .e-dnevnik.toml prebacis na server i od tad nadalje vise ne treba refreshati token na ruke.

Thanks na info, te sam korake i odradio prije nego što sam otvorio issue (osim što sam otvorio svoj Oauth2 i izgenerirao svoj calendar_credentials.json), iskreno, mislio sam da si ga stavio zabunom na github, pa nisam htio koristiti credentialse koje nisam ja izgenerirao, možda sam promašio koncept kako to "radi" i zapravo nije bilo potrebe to raditi, ali eto... Trebalo mi je malo vremena dok polovim zašto ne radi u dokeru, ali kad sam vidio u logovima da se u dokeru ne može pokrenuti browser, odradio sam na svom kompu i prekopirao fajle natrag na rpi, bot je proradio.

Bilo bi super da se može upisait testni event, čisto da se vidi jel sve dobro podešeno, ali evo danas je došla nova obavijest o ispitu i vidim da mi je upisano u kalendar (iako nemam potreban scope za upisivanje u kalendar?!)... 

![image](https://github.com/dkorunic/e-dnevnik-bot/assets/60796036/1c569fb0-2371-4ddc-9fd9-bcb1bae639ad)

**Comment by dkorunic** [comment]
@nsturko Imas, ovaj koji si naveo je full scope za sve. Sto se tice credentialsa, nije to zabunom, u ovom modelu (server-side) nema niceg specijalno tajnog u server credentialsima. Podaci iz njega se mogu hardkodirati u source, ali je ovaj nacin fleksibilniji i omogucava i korisnicima da imaju svoje credentialse ako ne vjeruju autoru (meni) :-)
Sto se tice testnog eventa, da, slozit cu nesto po tom pitanju, a i pitali su me da omogucim replay eventova u nekom vremenskom roku (zadnjih tjedan, dva, tri) tako da cu nesto napraviti za to. U svakom slucaju dok u logovima/journalu bota vidis da se Calendar API inicijalizirao, to znaci da je sve u redu.

**Comment by nsturko** [comment]
Thx, na objašnjenju, zatvaram issue :)
