### ISSUE TITLE
Ne šalje mi ocjene na Telegram.

### ISSUE THREAD

**Issue by Lvca1971** [dkorunic/e-dnevnik-bot#9]
Otkad je CARNet promijenio web više mi na Telegram ne stižu nove ocjene, samo novi najavljeni ispiti. Trebam li nešto promijeniti u postavkama ili...? Hvala.

**Comment by dkorunic** [comment]
Treba instalirati noviju verziju, najbolje bi bilo zadnju sa releaseova. Promijenili su lokaciju i nazivlje klasa u HTML-u koji se koriste za ocjene, tako da sam morao adaptirati kod dijela koji se bavi procesiranjem sadrzaja. Javi ako nesto i dalje ne radi, makar moralo bi.

**Comment by Lvca1971** [comment]
Je, to mi je prvo palo na pamet, verzija mi je aktualna zadnjih mjesec dana, trenutno 0.14.3., ali točno kad su prmijenili web meni su prestale doalziti poruke za ocjene...

**Comment by dkorunic** [comment]
@Lvca1971 Ajmo onda dalje debuggirati kroz mail, javi mi se na moje ime.prezime na Gmail sa logovima (sa `--verbose`) pa cemo vidjeti sto dalje.
